install.packages("strap")
install.packages("phytools")

library(phytools)
library(strap)
library(phyloch)

#Read BEAST tree (needs to be format generated by TreeAnnotator)
BEASTtree<-read.nexus("Isopoda.edit20.Oniscidates.SubM.LogNrml.mcc.tree")

#Read node heights
BEASTtree$root.time <- max(nodeHeights(BEASTtree))

#Read 
annot_tree <- phyloch::read.beast("Isopoda.edit20.Oniscidates.SubM.LogNrml.mcc.tree")

if (is.null(annot_tree$`CAheight_95%_HPD_MIN`)) {
  annot_tree$min_ages <- annot_tree$`height_95%_HPD_MIN`
  annot_tree$max_ages <- annot_tree$`height_95%_HPD_MAX`
} else {
  annot_tree$min_ages <- annot_tree$`CAheight_95%_HPD_MIN`
  annot_tree$max_ages <- annot_tree$`CAheight_95%_HPD_MAX`
}

annot_tree$root.time <- max(nodeHeights(annot_tree))
geoscalePhylo(ladderize(annot_tree, right = F), x.lim=c(-150, 450), units=c("Period", "Epoch"), boxes="Period")
#geoscalePhylo(ladderize(annot_tree, right = F), x.lim=c(-150, 450), units=c("Period", "Epoch", "Age"), boxes="Epoch")

T1 <- get("last_plot.phylo", envir = .PlotPhyloEnv)

for(i in (Ntip(annot_tree) + 1):(annot_tree$Nnode + Ntip(annot_tree))) {
       lines(x = c(T1$root.time - annot_tree$min_ages[i - Ntip(annot_tree)],
                   T1$root.time - annot_tree$max_ages[i - Ntip(annot_tree)] ),
             y = rep(T1$yy[i], 2), lwd = 3, lend = 0,
             col = make.transparent("darkgreen", 0.3))
}

BEASTtree$node.label <- round(annot_tree$posterior, 2)
nodelabels(BEASTtree$node.label, adj = c(1.15,1.5), frame="none", cex=(0.3))

BEASTtree$node.label <- round(annot_tree$height_median, 1)
nodelabels(BEASTtree$node.label, adj = c(1.15,-0.7), frame="none", cex=(0.3))

